name = input("Enter your name:")
father_name = input("Enter your Father's name:")
Age = input("Enter age:")
program = input("Program is:")
university = input("Enter University name:")

print("Name is:" + name)
print("Father's Name is:" + father_name)
print("Age is:" + Age)
print("Program is:" + program)
print("University is:" + university)
